# docker-compose.yml

version: '3.8'

networks:
  proxy:
    external: true
    name: proxy_network


services:
  frontend:
    image: docker.io/tbelbek/video-transcription-frontend:latest
    container_name: video-transcription-frontend
    volumes:
      - ./import:/app/import
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_CACHE_DIR=/model_cache/.cache
    networks:
      - proxy

  backend:
    image: docker.io/tbelbek/video-transcription-backend:latest
    container_name: video-transcription-backend
    volumes:
      - ./model_cache:/model_cache/.cache
      - ./import:/app/import
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_CACHE_DIR=/model_cache/.cache
    networks:
      - proxy
    depends_on:
      - frontend

  # Optional: SQLite Database Service (if you prefer a separate DB service)
  # Not necessary since both frontend and backend access the same SQLite DB via shared volume