version: '3.8'

networks:
  proxy:
    external: true
    name: proxy_network

services:
  app:
    image: tbelbek/video-transcription-app:latest
    volumes:
      - ./import/uploads:/app/import/uploads
      - ./import/audio:/app/import/audio
      - ./import/transcriptions:/app/import/transcriptions
      - ./import/summaries:/app/import/summaries
      - ./transcriptions.db:/app/transcriptions.db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    networks:
      - proxy